import os
from dotenv import load_dotenv

load_dotenv()

FM_API_PROFILE_ENDPOINT = os.getenv("NEXT_PUBLIC_FM_API_PROFILE_ENDPOINT")
FM_API_SESSIONS_ENDPOINT = os.getenv("NEXT_PUBLIC_FM_API_SESSIONS_ENDPOINT")
FM_API_URL = os.getenv("NEXT_PUBLIC_FM_API_URL")

ENCRYPTION_KEY_STR = os.getenv("ENCRYPTION_KEY")
ENCRYPTION_AES_IV = os.getenv("ENCRYPTION_AES_IV")

SESSION_COOKIE_NAME = os.getenv("NEXT_PUBLIC_SESSION_COOKIE_NAME")

SUPABASE_PROJECT_URL = os.getenv("SUPABASE_PROJECT_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
