/**
 * From Focusmate Profile API
 * https://apidocs.focusmate.com/#8f4fe5e5-0774-46ce-8010-5ed082c4f581
 */
export interface FocusmateProfile {
  user: FocusmateUser
}

export interface FocusmateUser {
  userId: string
  name: string
  totalSessionCount: number
  timeZone: string
  photoUrl: string
  memberSince: string
}

// Supabase `profile` table schema
export interface DbUser {
  // Auto-generated by Supabase
  created_at?: string

  // FocusmateUser-equivalent
  user_id: string // primary key
  total_session_count: number | null
  time_zone: string | null
  member_since: string | null

  // For session management
  access_token_encrypted: string
  session_id: string

  // TODO: Let users set their own preferences
  late_after_seconds: number
}
