/**
 * From Focusmate Profile API
 * https://apidocs.focusmate.com/#8f4fe5e5-0774-46ce-8010-5ed082c4f581
 */
export interface FmProfile {
  user: FmUser
}
export interface FmUser {
  userId: string
  name: string
  totalSessionCount: number
  timeZone: string
  photoUrl: string
  memberSince: string
}

/**
 * Supabase `profile` table schema
 *
 * Certain fields are nullable to accommodate porting of data
 * from `user` table of FocusBeacon v1.0
 */
export interface DbProfile {
  // Auto-generated by Supabase
  created_at?: string

  // FmUser-equivalent
  user_id: string // primary key
  total_session_count: number | null
  time_zone: string
  member_since: string | null

  // For session management
  access_token_encrypted: string | null
  session_id: string | null

  // TODO: Let users set their own preferences
  late_after_seconds?: number // default: 120
  include_weekend_in_daily_streak?: boolean // default: false
}

/**
 * From Focusmate Sessions API
 * https://apidocs.focusmate.com/#6e343d29-8cbc-4420-b44f-0e6b9ac13547
 */
export interface FmSessions {
  sessions: FmSession[]
}
export interface FmSession {
  sessionId: string
  duration: number
  startTime: string
  // If the session is incomplete, aka users[0].completed === false,
  // then users[1] will be undefined and users[0].joinedAt might be null
  users: FmSessionUser[]
}
export interface FmSessionUser {
  userId: string
  requestedAt?: string
  joinedAt?: string | null
  completed?: boolean
  sessionTitle?: string | null
}

/**
 * Supabase `sessions` table schema
 */
export interface DbSession {
  // Auto-generated by Supabase
  created_at?: string

  // FmSession-equivalent
  session_id: string // primary key
  duration: number
  start_time_utc: string
  requested_at_utc: string
  joined_at_utc: string | null // might be NULL if session is incomplete
  completed: boolean
  session_title: string // empty string if not entered by user
  partner_id: string | null // users[1].userId; NULL if session is incomplete
  user_id: string | null // users[0].userId; NULL if user is deleted in db
}
